[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"
[[mgr.prepend_keymap]]
on = ["q"]
run = "quit --no-cwd-file"
desc = "Quit yazi"
[[mgr.prepend_keymap]]
on = ["Q"]
run = "quit"
desc = "Quit yazi and cd into dir"
[[mgr.prepend_keymap]]
on  = ["Y"]
run = "plugin copy-file-to-clipboard"
desc = "Copy file contents to clipboard"
[[mgr.prepend_keymap]]
on  = "_"
run = "plugin back-cwd"
desc = "Return to initial directory"
[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
[[mgr.prepend_keymap]]
on   = "<Right>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
on   = "o"
run  = "create"
desc = "Create a file or a directory"
[[mgr.prepend_keymap]]
on   = "<Esc>"
run  = ["unyank", "escape"]
desc = "Clear selection and unyank"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.append_keymap]]
on = ["g", "?"]
run = "help"
desc = "Open help menu"

[[help.append_keymap]]
on = ["q"]
run = "close"
desc = "Quit help menu"
[[help.append_keymap]]
on = ["/"]
run = "filter"
desc = "Filter help menu"
