force_keyboard_focus = true
close_when_open = true
click_to_close = true
single_click_activation = true
selection_wrap = false
global_argument_delimiter = "#"
exact_search_prefix = "'"
theme = "gruvbox"
resume_last_query = false
hide_return_action = true
hide_action_hints = true

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search...", list = "No Results" }
"desktopapplications" = { input = "Applications", list = "No Applications" }
"calc" = { input = "Calculate", list = "No Result" }
"clipboard" = { input = "Clipboard", list = "Clipboard Empty" }
"archlinuxpkgs" = { input = "Search Arch packages", list = "No Packages" }
"runner" = { input = "Run command", list = "No Command" }

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl m"]
resume_last_query = ["ctrl r"]
quick_activate = ["ctrl n", "ctrl e", "ctrl i", "ctrl a"]

[providers]
default = ["desktopapplications", "calc", "runner"]
empty = ["desktopapplications"]
ignore_preview = []
max_results = 50

[providers.max_results_provider]
calc = 20
clipboard = 20
archlinuxpkgs = 15
runner = 8

[providers.clipboard]
time_format = "relative"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix = "~"
provider = "archlinuxpkgs"

[[providers.prefixes]]
prefix = ">"
provider = "runner"
